import 'package:flutter/material.dart';
import '../../../../config/theme.dart';
import '../../../../utils/validators.dart';

/// Step 1: Tenant Info (nome, domain, tipo, admin info)
class TenantInfoStep extends StatefulWidget {
  final String initialName;
  final String initialDomain;
  final String initialTenantType;
  final String initialAdminEmail;
  final String initialAdminPhone;
  final String initialAdminFirstName;
  final String initialAdminLastName;
  final Function({
    required String name,
    required String domain,
    required String tenantType,
    required String adminEmail,
    required String adminPhone,
    required String adminFirstName,
    required String adminLastName,
  })
  onNext;

  const TenantInfoStep({
    super.key,
    required this.initialName,
    required this.initialDomain,
    required this.initialTenantType,
    required this.initialAdminEmail,
    required this.initialAdminPhone,
    required this.initialAdminFirstName,
    required this.initialAdminLastName,
    required this.onNext,
  });

  @override
  State<TenantInfoStep> createState() => _TenantInfoStepState();
}

class _TenantInfoStepState extends State<TenantInfoStep> {
  final _formKey = GlobalKey<FormState>();
  late final TextEditingController _nameController;
  late final TextEditingController _domainController;
  late final TextEditingController _adminEmailController;
  late final TextEditingController _adminPhoneController;
  late final TextEditingController _adminFirstNameController;
  late final TextEditingController _adminLastNameController;
  late String _selectedTenantType;

  @override
  void initState() {
    super.initState();
    _nameController = TextEditingController(text: widget.initialName);
    _domainController = TextEditingController(text: widget.initialDomain);
    _adminEmailController = TextEditingController(
      text: widget.initialAdminEmail,
    );
    _adminPhoneController = TextEditingController(
      text: widget.initialAdminPhone,
    );
    _adminFirstNameController = TextEditingController(
      text: widget.initialAdminFirstName,
    );
    _adminLastNameController = TextEditingController(
      text: widget.initialAdminLastName,
    );
    _selectedTenantType = widget.initialTenantType;

    // Auto-generate domain from name
    _nameController.addListener(_autoGenerateDomain);
  }

  @override
  void dispose() {
    _nameController.removeListener(_autoGenerateDomain);
    _nameController.dispose();
    _domainController.dispose();
    _adminEmailController.dispose();
    _adminPhoneController.dispose();
    _adminFirstNameController.dispose();
    _adminLastNameController.dispose();
    super.dispose();
  }

  void _autoGenerateDomain() {
    if (_domainController.text.isEmpty || _isAutoGenerated) {
      final name = _nameController.text;
      final domain = name
          .toLowerCase()
          .replaceAll(RegExp(r'[^a-z0-9\s-]'), '')
          .replaceAll(RegExp(r'\s+'), '-')
          .replaceAll(RegExp(r'-+'), '-')
          .trim();
      _domainController.text = domain;
    }
  }

  bool get _isAutoGenerated {
    final name = _nameController.text;
    final domain = _domainController.text;
    final generatedDomain = name
        .toLowerCase()
        .replaceAll(RegExp(r'[^a-z0-9\s-]'), '')
        .replaceAll(RegExp(r'\s+'), '-')
        .replaceAll(RegExp(r'-+'), '-')
        .trim();
    return domain == generatedDomain;
  }

  void _handleNext() {
    if (_formKey.currentState!.validate()) {
      widget.onNext(
        name: _nameController.text.trim(),
        domain: _domainController.text.trim().toLowerCase(),
        tenantType: _selectedTenantType,
        adminEmail: _adminEmailController.text.trim(),
        adminPhone: _adminPhoneController.text.trim(),
        adminFirstName: _adminFirstNameController.text.trim(),
        adminLastName: _adminLastNameController.text.trim(),
      );
    }
  }

  @override
  Widget build(BuildContext context) {
    return SingleChildScrollView(
      padding: const EdgeInsets.all(24),
      child: Form(
        key: _formKey,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            const Text('Informazioni Tenant', style: AppTextStyles.h3),
            const SizedBox(height: 8),
            const Text(
              'Inserisci le informazioni base del tenant e dell\'amministratore principale',
              style: AppTextStyles.caption,
            ),
            const SizedBox(height: 32),

            // Nome Tenant
            TextFormField(
              controller: _nameController,
              decoration: const InputDecoration(
                labelText: 'Nome Tenant *',
                hintText: 'es: Salone Bellezza Roma',
                prefixIcon: Icon(Icons.business),
              ),
              validator: (value) => Validators.minLength(value, 3, 'Nome'),
              textInputAction: TextInputAction.next,
            ),
            const SizedBox(height: 16),

            // Domain
            TextFormField(
              controller: _domainController,
              decoration: InputDecoration(
                labelText: 'Dominio *',
                hintText: 'es: roma',
                prefixIcon: const Icon(Icons.language),
                suffixText: '.beautyflow.it',
                helperText:
                    'Il dominio viene generato automaticamente dal nome',
              ),
              validator: Validators.domain,
              textInputAction: TextInputAction.next,
              onChanged: (value) {
                // Convert to lowercase on change
                if (value != value.toLowerCase()) {
                  _domainController.value = _domainController.value.copyWith(
                    text: value.toLowerCase(),
                    selection: TextSelection.collapsed(offset: value.length),
                  );
                }
              },
            ),
            const SizedBox(height: 24),

            // Tenant Type
            DropdownButtonFormField<String>(
              value: _selectedTenantType,
              decoration: const InputDecoration(
                labelText: 'Tipo di Attività *',
                hintText: 'Seleziona il tipo di attività',
                prefixIcon: Icon(Icons.store),
              ),
              items: const [
                DropdownMenuItem(
                  value: 'HAIRDRESSER',
                  child: Row(
                    children: [
                      Icon(Icons.content_cut, size: 20),
                      SizedBox(width: 8),
                      Text('Parrucchiere'),
                    ],
                  ),
                ),
                DropdownMenuItem(
                  value: 'BARBER',
                  child: Row(
                    children: [
                      Icon(Icons.cut, size: 20),
                      SizedBox(width: 8),
                      Text('Barbiere'),
                    ],
                  ),
                ),
                DropdownMenuItem(
                  value: 'BEAUTICIAN',
                  child: Row(
                    children: [
                      Icon(Icons.face, size: 20),
                      SizedBox(width: 8),
                      Text('Estetista'),
                    ],
                  ),
                ),
                DropdownMenuItem(
                  value: 'SPA',
                  child: Row(
                    children: [
                      Icon(Icons.spa, size: 20),
                      SizedBox(width: 8),
                      Text('Spa'),
                    ],
                  ),
                ),
              ],
              onChanged: (value) {
                if (value != null) {
                  setState(() {
                    _selectedTenantType = value;
                  });
                }
              },
            ),
            const SizedBox(height: 32),

            const Divider(),
            const SizedBox(height: 24),

            const Text('Dati Amministratore', style: AppTextStyles.h3),
            const SizedBox(height: 16),

            // Admin Email
            TextFormField(
              controller: _adminEmailController,
              decoration: const InputDecoration(
                labelText: 'Email Amministratore *',
                hintText: 'admin@esempio.it',
                prefixIcon: Icon(Icons.email),
              ),
              validator: Validators.email,
              keyboardType: TextInputType.emailAddress,
              textInputAction: TextInputAction.next,
            ),
            const SizedBox(height: 16),

            // Admin Phone
            TextFormField(
              controller: _adminPhoneController,
              decoration: const InputDecoration(
                labelText: 'Telefono Amministratore *',
                hintText: '+39 333 123 4567',
                prefixIcon: Icon(Icons.phone),
              ),
              validator: Validators.phone,
              keyboardType: TextInputType.phone,
              textInputAction: TextInputAction.next,
            ),
            const SizedBox(height: 16),

            // Admin First Name & Last Name (row)
            Row(
              children: [
                Expanded(
                  child: TextFormField(
                    controller: _adminFirstNameController,
                    decoration: const InputDecoration(
                      labelText: 'Nome *',
                      hintText: 'Mario',
                      prefixIcon: Icon(Icons.person),
                    ),
                    validator: (value) =>
                        Validators.minLength(value, 2, 'Nome'),
                    textInputAction: TextInputAction.next,
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: TextFormField(
                    controller: _adminLastNameController,
                    decoration: const InputDecoration(
                      labelText: 'Cognome *',
                      hintText: 'Rossi',
                      prefixIcon: Icon(Icons.person_outline),
                    ),
                    validator: (value) =>
                        Validators.minLength(value, 2, 'Cognome'),
                    textInputAction: TextInputAction.done,
                    onFieldSubmitted: (_) => _handleNext(),
                  ),
                ),
              ],
            ),
            const SizedBox(height: 32),

            // Info Box
            Container(
              padding: const EdgeInsets.all(16),
              decoration: BoxDecoration(
                color: AppColors.info.withOpacity(0.1),
                borderRadius: BorderRadius.circular(8),
                border: Border.all(color: AppColors.info.withOpacity(0.3)),
              ),
              child: Row(
                children: [
                  Icon(Icons.info_outline, color: AppColors.info),
                  const SizedBox(width: 12),
                  Expanded(
                    child: Text(
                      'L\'amministratore riceverà una password temporanea via email e dovrà cambiarla al primo accesso.',
                      style: AppTextStyles.bodySmall.copyWith(
                        color: AppColors.info,
                      ),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 32),

            // Next Button
            SizedBox(
              width: double.infinity,
              child: ElevatedButton.icon(
                onPressed: _handleNext,
                icon: const Icon(Icons.arrow_forward),
                label: const Text('Avanti'),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
